version: "3.7"
services:
  django:
    # コンテナ名
    container_name: django
    # ビルドするdockerファイルが格納されたディレクトリ
    build: ./app
    # 正常起動後に実行するコマンド
    command: python3 manage.py runserver 0.0.0.0:7070
    volumes:
      # マウントするディレクトリ
      - ./app:/usr/src/app/
    ports:
      # ホスト側のポート：コンテナ側のポート
      - 7070:7070
    env_file:
      # 環境変数に設定するファイル
      - ./app/.env
    depends_on:
      # 接続するサービス
      - postgres

  postgres:
    container_name: postgrespy
    build: ./postgres
    volumes:
      # DBのデータはボリュームを作成して保存
      # ディレクトリとマウントとって実データをホストOSに直接残しても良い
      # /var/lib/postgresql/dataにDBのデータが格納されている
      - sample_postgis_data:/var/lib/postgresql/data
      # down -vなどでボリュームがない時などを含めた初回起動時に実行されるファイルを指定
      - ./postgres/sql:/docker-entrypoint-initdb.d
    env_file: ./postgres/.env_db
    ports:
      # ホスト側のポートはローカルのpsqlとバッティングするので5432以外にする
      - 45432:5432

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./django/static:/usr/src/app/static
    ports:
      - 70:70
    depends_on:
      - django

volumes:
  sample_postgis_data: