# Generated by Django 3.0.6 on 2022-10-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MYoutubeChannelModel',
            fields=[
                ('channel_id', models.CharField(help_text='YoutubeチャンネルのID', max_length=200, primary_key=True, serialize=False)),
                ('channel_title', models.CharField(help_text='Youtubeチャンネルタイトル', max_length=200)),
                ('created', models.DateTimeField(help_text='作成日')),
                ('modified', models.DateTimeField(help_text='更新日')),
                ('deleted', models.BooleanField(help_text='削除日')),
            ],
            options={
                'db_table': 'm_youtube_channel_model',
            },
        ),
    ]
